#!/bin/bash

set -e

if [[ $(whoami) =~ ^suzen(5|9|901)$ ]]; then
  NETWORK=$(whoami)_network_$RANDOM
  docker network create --internal ${NETWORK} 2>&1 1>/dev/null

  # server
  /usr/bin/docker run -d --rm --network $NETWORK --cpus=".2" \
    --memory=50m --kernel-memory=50m --pids-limit=50 --stop-timeout=3600 \
    {{ registry_url }}/suzenescape/$(whoami)server 2>&1 1>/dev/null

  # task
  /usr/bin/docker run -it --rm --network $NETWORK --cpus=".2" \
    --memory=50m --kernel-memory=50m --pids-limit=50 --stop-timeout=3600 \
    {{ registry_url }}/suzenescape/$(whoami) 2>/dev/null

  docker network rm ${NETWORK} 2>&1 1>/dev/null

else
  # task
  /usr/bin/docker run -it --rm --network none --cpus=".2" \
    --memory=50m --kernel-memory=50m --pids-limit=50 --stop-timeout=3600 \
    {{ registry_url }}/suzenescape/$(whoami) 2>/dev/null
fi
